export const CREATE_SUPPLIER = "CREATE_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const FETCH_SUPPLIER = "FETCH_SUPPLIER";

export const ADD_TENDER_STARTED = "ADD_TENDER_STARTED";
export const ADD_TENDER_SUCCESS = "ADD_TENDER_SUCCESS";
export const ADD_TENDER_FAILURE = "ADD_TENDER_FAILURE";
