export const CREATE_SUPPLIER='CREATE_SUPPLIER'
export const DELETE_SUPPLIER='DELETE_SUPPLIER'
export const SET_SUPPLIER='SET_SUPPLIER'
export const UPDATE_SUPPLIER='UPDATE_SUPPLIER'

export const ADD_SUPPLIER_STARTED = "ADD_SUPPLIER_STARTED";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_FAILURE = "ADD_SUPPLIER_FAILURE";
